#!/bin/bash

set -x
# Copy buildroot defconfig and build it

echo "Configure ignition buildroot"
cp scripts/ignition_defconfig buildroot/configs
(cd buildroot && make ignition_defconfig)

echo "Checking if qmake is already built"
if [ ! -f  buildroot/output/host/usr/bin/qmake ]; then
	(cd buildroot && make)
fi

# Now use qmake that is generated by buildroot and build ignition
echo "Building ignition"
(cd ignition; ../buildroot/output/host/usr/bin/qmake; make clean; make)

# Copy the ignition binary to the buildroot filesystem
echo "Copying ignition"
cp ignition/ignition buildroot/output/target/usr/bin

# Rebuild buildroot; this will add ignition to the root filesystem
echo "Rebuilding ignition for the second time"
(cd buildroot && make)
